import Head from "next/head";
import Box from "@mui/material/Box";

import Header from "./Header";
import Footer from "./Footer";

const Layout = ({ isIndex, children }) => {
  return (
    <>
      <Head>
        <title>My ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&subset=japanese"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <Box sx={styles.outerBox}>
        <Header isIndex={isIndex} />
        <Box sx={styles.box}>{children}</Box>
        <Footer />
      </Box>
    </>
  );
};

const styles = {
  outerBox: {
    minHeight: "100vh",
    position: "relative",
    paddingBottom: 8,
  },
  box: {
    maxWidth: "lg",
    mx: "auto",
    px: 5,
    pt: 11,
  },
};

export default Layout;
