import Button from "@mui/material/Button";
import DeleteIcon from "@mui/icons-material/Delete";
import Link from "next/link";
import { useRecoilValue } from "recoil";
import { todosState } from "../components/atoms";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const todos = useRecoilValue(todosState);
  return (
    <>
      <Head>
        <title>My ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        hello My ToDo App
        <Button variant="contained">Hello World</Button>
        <DeleteIcon />
        {todos.map((todo) => (
          <div key={todo.id}>
            <h1>{todo.title}</h1>
            <p>{todo.status}</p>
          </div>
        ))}
      </div>
    </>
  );
}
